In [1]:
import pandas as pd
import requests

In [2]:
response=requests.get('https://api.themoviedb.org/3/trending/movie/day?api_key="api_key')

In [4]:
df=pd.DataFrame(response.json()['results'])[['id','title','overview','popularity','overview','vote_average','vote_count']]

In [5]:
df.shape

(20, 7)

In [6]:
df=pd.DataFrame()

In [7]:
df

Empty DataFrame
Columns: []
Index: []

In [9]:
import requests

url = "https://api.themoviedb.org/3/discover/movie"

params = {
    "api_key": "api_key",
    "page": 1
}

response = requests.get(url, params=params, timeout=10)

print(response.status_code)
print(response.json())

200
{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/pq1Mhdt9LbkQM5TOjuVZpcczbf.jpg', 'genre_ids': [878, 28, 12], 'id': 969681, 'title': 'Spider-Man: Brand New Day', 'original_language': 'en', 'original_title': 'Spider-Man: Brand New Day', 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.", 'popularity': 1110.545, 'poster_path': '/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg', 'release_date': '2026-07-29', 'softcore': False, 'video': False, 'vote_average': 7.884, 'vote_count': 2258}, {'adult': False, 'backdrop_path': '/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg', 'genre_ids': [12, 28, 14], 'id': 1368337, 'title': 'The Odyssey', 'original_language': 'en', 'original_title': 'The Odyssey', 'overview': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.', 'popularity': 586.1293, 'poster_path': '/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg', 'release_date': '2026-07-15', 'softcore': False, 'video': False, 'vote_average': 7.987, 'vote_count': 3304}, {'adult': False, 'backdrop_path': '/qDa0fqDqIBCovRp975RvtGPcuN3.jpg', 'genre_ids': [28, 53], 'id': 1288445, 'title': 'Mutiny', 'original_language': 'en', 'original_title': 'Mutiny', 'overview': "After witnessing his billionaire boss' murder and being framed for the crime, Cole Reed boards a cargo ship on a one-man crusade to avenge his boss' death only to discover an international conspiracy.", 'popularity': 472.8163, 'poster_path': '/iYhvs0hLGtZZt6qDrUnuM0E1zGM.jpg', 'release_date': '2026-08-19', 'softcore': False, 'video': False, 'vote_average': 6.349, 'vote_count': 225}, {'adult': False, 'backdrop_path': '/zFCWfU2ViMIm38G1W8UsnSpqmWn.jpg', 'genre_ids': [10749, 18], 'id': 1516698, 'title': 'The Last Sunrise', 'original_language': 'en', 'original_title': 'The Last Sunrise', 'overview': "Ry, a college student with a chronic illness, escapes to Mallorca for the summer with her mother, where she unexpectedly falls for a local and begins to embrace living in the moment. But as her condition worsens and long-hidden family secrets come to light, everything she has found before summer's end is threatened.", 'popularity': 308.5632, 'poster_path': '/3PWJqDfygN0YNNjWsDUOXclCp3h.jpg', 'release_date': '2026-08-26', 'softcore': False, 'video': False, 'vote_average': 7.2, 'vote_count': 46}, {'adult': False, 'backdrop_path': '/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg', 'genre_ids': [80, 28, 53], 'id': 1621552, 'title': 'Facing El Chapo', 'original_language': 'es', 'original_title': 'La captura', 'overview': 'Two Mexican officers must survive the final hours of their shift after crossing a ruthless cartel boss.', 'popularity': 298.9748, 'poster_path': '/alpf5v4UqSFawPmG9RX03Or4BDk.jpg', 'release_date': '2026-08-21', 'softcore': False, 'video': False, 'vote_average': 8.73, 'vote_count': 315}, {'adult': False, 'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg', 'genre_ids': [27, 53], 'id': 1339713, 'title': 'Obsession', 'original_language': 'en', 'original_title': 'Obsession', 'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.', 'popularity': 250.0668, 'poster_path': '/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg', 'release_date': '2026-05-13', 'softcore': False, 'video': False, 'vote_average': 8.2, 'vote_count': 5146}, {'adult': False, 'backdrop_path': '/z7lZgL5tzefTfhyRtouThFhsuUS.jpg', 'genre_ids': [28, 878, 53], 'id': 1323244, 'title': 'Rage of Stars', 'original_language': 'en', 'original_title': 'Rage of Stars', 'overview': 'A story about a woman from the International Special Forces Unit, who has a premonition about the impending end of humanity.', 'popularity': 242.8335, 'poster_path': '/oLld47ZT1I3iecM3OWhIphohQUJ.jpg', 'release_date': '2026-08-06', 'softcore': False, 'video': False, 'vote_average': 5.551, 'vote_count': 49}, {'adult': False, 'backdrop_path': '/8sSKdEmlmqF4kJUd28SqthXC4yZ.jpg', 'genre_ids': [16, 10751, 35, 12], 'id': 1084244, 'title': 'Toy Story 5', 'original_language': 'en', 'original_title': 'Toy Story 5', 'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.", 'popularity': 239.7891, 'poster_path': '/sfQtVlIHljToOwYjhe21KPGzZWK.jpg', 'release_date': '2026-06-17', 'softcore': False, 'video': False, 'vote_average': 8.266, 'vote_count': 1762}, {'adult': False, 'backdrop_path': '/tBRSSfgqOAq7YlG8udcoJIBm2FG.jpg', 'genre_ids': [28, 80, 18], 'id': 1213243, 'title': 'Toxic: A Fairy Tale for Grown-ups', 'original_language': 'kn', 'original_title': 'ಟಾಕ್ಸಿಕ್', 'overview': 'A powerful drug cartel pulls the strings behind a facade of sun-soaked beaches as a gritty, violent underworld power struggle emerges during the crumbling of Portuguese colonial rule.', 'popularity': 204.7834, 'poster_path': '/oiIPU4lvnI0Ag2K9cyAi44eCaoE.jpg', 'release_date': '2026-08-26', 'softcore': False, 'video': False, 'vote_average': 6.842, 'vote_count': 19}, {'adult': False, 'backdrop_path': '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg', 'genre_ids': [10751, 14, 35, 12], 'id': 1108427, 'title': 'Moana', 'original_language': 'en', 'original_title': 'Moana', 'overview': "Teenage Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with infamous demigod Maui on an unforgettable journey to restore prosperity to her people.", 'popularity': 191.6542, 'poster_path': '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg', 'release_date': '2026-07-08', 'softcore': False, 'video': False, 'vote_average': 6.149, 'vote_count': 248}, {'adult': False, 'backdrop_path': '/yjK3ardrgdS8suZG8KMU82Q7U38.jpg', 'genre_ids': [10749], 'id': 1285366, 'title': 'Shape of My Heart', 'original_language': 'ja', 'original_title': '愛のぬくもり', 'overview': 'A romance about a man and a woman who, due to an unexpected event, end up switching bodies. Despite coming from completely different backgrounds and environments, the two try to overcome the various difficulties that arise from their body swap.', 'popularity': 190.7725, 'poster_path': '/3r0O6BW9USoZ9mteCVyNKMQriRL.jpg', 'release_date': '2024-07-06', 'softcore': False, 'video': False, 'vote_average': 6.2, 'vote_count': 4}, {'adult': False, 'backdrop_path': '/dNKFETDDujxm2PUN873Jwiw5VML.jpg', 'genre_ids': [27, 14, 9648], 'id': 1232569, 'title': 'Pinocchio: Unstrung', 'original_language': 'en', 'original_title': 'Pinocchio: Unstrung', 'overview': 'Influenced by a sinister Cricket and created by Geppetto, Pinocchio launches a violent crusade to carve himself into a real boy like his brother James, one piece at a time.', 'popularity': 181.433, 'poster_path': '/eUJXk3bTvLBi5Zcb0BCedZU7lVL.jpg', 'release_date': '2026-07-22', 'softcore': False, 'video': False, 'vote_average': 6.754, 'vote_count': 67}, {'adult': False, 'backdrop_path': '/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg', 'genre_ids': [12, 16, 35, 10751, 14], 'id': 1315772, 'title': 'Minions & Monsters', 'original_language': 'en', 'original_title': 'Minions & Monsters', 'overview': 'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.', 'popularity': 177.9936, 'poster_path': '/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg', 'release_date': '2026-06-24', 'softcore': False, 'video': False, 'vote_average': 7.553, 'vote_count': 925}, {'adult': False, 'backdrop_path': '/uyrOU4BDm2kbVxFsMiDFIHDhc4d.jpg', 'genre_ids': [28, 12, 878], 'id': 634649, 'title': 'Spider-Man: No Way Home', 'original_language': 'en', 'original_title': 'Spider-Man: No Way Home', 'overview': 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', 'popularity': 159.4572, 'poster_path': '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', 'release_date': '2021-12-15', 'softcore': False, 'video': False, 'vote_average': 7.944, 'vote_count': 22914}, {'adult': False, 'backdrop_path': '/wcUohmHc9oDZXarXDp905TYVui4.jpg', 'genre_ids': [18, 10749], 'id': 82023, 'title': 'Hotel Desire', 'original_language': 'de', 'original_title': 'Hotel Desire', 'overview': 'Antonia is a single mother who works as a hotel maid in Berlin. A normal hot summer day takes a dramatic turn when she crosses paths with a particular guest of the hotel, famous blind portrait painter Julius Pass.', 'popularity': 147.2661, 'poster_path': '/47XRWH95ATv4szxdWHl723guWXP.jpg', 'release_date': '2011-12-07', 'softcore': False, 'video': False, 'vote_average': 6.163, 'vote_count': 160}, {'adult': False, 'backdrop_path': '/vcZ3UUVmFNk90DBSrTBlTKCdbbE.jpg', 'genre_ids': [35, 18, 53], 'id': 1130948, 'title': 'Rosebush Pruning', 'original_language': 'en', 'original_title': 'Rosebush Pruning', 'overview': 'In a Spanish villa, American siblings Jack, Ed, Anna and Robert wallow in isolation and their inherited fortune. When Jack wants to move in with his girlfriend and Ed uncovers the truth about their mother’s death, the fabric of the family begins to unravel.', 'popularity': 136.9485, 'poster_path': '/tXsTtSgguTsk5J115jokwK55awF.jpg', 'release_date': '2026-04-23', 'softcore': False, 'video': False, 'vote_average': 6.117, 'vote_count': 30}, {'adult': False, 'backdrop_path': '/dqmMWNWfLnExDRpMtIMqI97GQFR.jpg', 'genre_ids': [27, 9648, 878], 'id': 1083381, 'title': 'Backrooms', 'original_language': 'en', 'original_title': 'Backrooms', 'overview': 'A strange doorway appears in the basement of a furniture showroom.', 'popularity': 135.0936, 'poster_path': '/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg', 'release_date': '2026-05-27', 'softcore': False, 'video': False, 'vote_average': 7.1, 'vote_count': 3018}, {'adult': False, 'backdrop_path': '/84FEpVVbSKYvKXDZJDZXOKBxCEm.jpg', 'genre_ids': [28, 27, 878], 'id': 1375646, 'title': 'Colony', 'original_language': 'ko', 'original_title': '군체', 'overview': 'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.', 'popularity': 132.6035, 'poster_path': '/tN799oUR0f1gUKDYdMNrDaY7I51.jpg', 'release_date': '2026-05-21', 'softcore': False, 'video': False, 'vote_average': 8.101, 'vote_count': 632}, {'adult': False, 'backdrop_path': '/caBIySpwuFi2i7ynvHIlnxJLOdN.jpg', 'genre_ids': [16, 28, 12, 878, 80, 18], 'id': 1560520, 'title': 'Batman: Knightfall Part 1: Knightfall', 'original_language': 'en', 'original_title': 'Batman: Knightfall Part 1: Knightfall', 'overview': 'Arkham Asylum has been destroyed, and all its inmates have been unleashed upon Gotham City. As Batman races to round up some of his greatest enemies, he is pushed to his physical and mental limits and into a final confrontation with a new threat: the man called Bane!', 'popularity': 123.2178, 'poster_path': '/360qdtu2hLnqMu8SVHMywn420w1.jpg', 'release_date': '2026-06-23', 'softcore': False, 'video': False, 'vote_average': 9.087, 'vote_count': 121}, {'adult': False, 'backdrop_path': '/flxau5Iu7bChQHsESqvGZ3FQRaI.jpg', 'genre_ids': [878, 53], 'id': 1275779, 'title': 'Disclosure Day', 'original_language': 'en', 'original_title': 'Disclosure Day', 'overview': "A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there's life beyond our understanding.", 'popularity': 121.7004, 'poster_path': '/AnJ8IQJI23hNpYXVNaythu061Ru.jpg', 'release_date': '2026-06-10', 'softcore': False, 'video': False, 'vote_average': 7.472, 'vote_count': 3089}], 'total_pages': 58671, 'total_results': 1173404}

In [15]:
import requests
import pandas as pd
import time

df = pd.DataFrame()

session = requests.Session()

for i in range(1, 200):

    while True:
        try:
            response = session.get(
                "https://api.themoviedb.org/3/discover/movie",
                params={
                    "api_key": "api_key",
                    "page": i
                },
                timeout=20
            )

            print("Page:", i, "Status:", response.status_code)

            if response.status_code == 200:
                data = response.json()

                temp_df = pd.DataFrame(data["results"])[
                    ["id", "title", "overview", "popularity", "vote_average", "vote_count"]
                ]

                df = pd.concat([df, temp_df], ignore_index=True)

                break

            else:
                print(response.text)
                break

        except requests.exceptions.ConnectionError:
            print("Connection error. Retrying page", i)
            time.sleep(5)

    time.sleep(2)

print(df.shape)

Page: 1 Status: 200
Page: 2 Status: 200
Page: 3 Status: 200
Page: 4 Status: 200
Page: 5 Status: 200
Page: 6 Status: 200
Page: 7 Status: 200
Page: 8 Status: 200
Page: 9 Status: 200
Page: 10 Status: 200
Page: 11 Status: 200
Page: 12 Status: 200
Page: 13 Status: 200
Page: 14 Status: 200
Page: 15 Status: 200
Page: 16 Status: 200
Page: 17 Status: 200
Page: 18 Status: 200
Page: 19 Status: 200
Page: 20 Status: 200
Page: 21 Status: 200
Page: 22 Status: 200
Page: 23 Status: 200
Page: 24 Status: 200
Page: 25 Status: 200
Page: 26 Status: 200
Page: 27 Status: 200
Page: 28 Status: 200
Page: 29 Status: 200
Page: 30 Status: 200
Page: 31 Status: 200
Page: 32 Status: 200
Page: 33 Status: 200
Page: 34 Status: 200
Page: 35 Status: 200
Page: 36 Status: 200
Page: 37 Status: 200
Page: 38 Status: 200
Page: 39 Status: 200
Page: 40 Status: 200
Page: 41 Status: 200
Page: 42 Status: 200
Page: 43 Status: 200
Page: 44 Status: 200
Page: 45 Status: 200
Page: 46 Status: 200
Page: 47 Status: 200
Page: 48 Status: 200
Page: 49 Status: 200
Page: 50 Status: 200
Page: 51 Status: 200
Page: 52 Status: 200
Page: 53 Status: 200
Page: 54 Status: 200
Page: 55 Status: 200
Page: 56 Status: 200
Page: 57 Status: 200
Page: 58 Status: 200
Page: 59 Status: 200
Page: 60 Status: 200
Page: 61 Status: 200
Page: 62 Status: 200
Page: 63 Status: 200
Page: 64 Status: 200
Page: 65 Status: 200
Page: 66 Status: 200
Page: 67 Status: 200
Page: 68 Status: 200
Page: 69 Status: 200
Page: 70 Status: 200
Page: 71 Status: 200
Page: 72 Status: 200
Page: 73 Status: 200
Page: 74 Status: 200
Page: 75 Status: 200
Page: 76 Status: 200
Page: 77 Status: 200
Page: 78 Status: 200
Page: 79 Status: 200
Page: 80 Status: 200
Page: 81 Status: 200
Page: 82 Status: 200
Page: 83 Status: 200
Page: 84 Status: 200
Page: 85 Status: 200
Page: 86 Status: 200
Page: 87 Status: 200
Page: 88 Status: 200
Page: 89 Status: 200
Page: 90 Status: 200
Page: 91 Status: 200
Page: 92 Status: 200
Page: 93 Status: 200
Page: 94 Status: 200
Page: 95 Status: 200
Page: 96 Status: 200
Page: 97 Status: 200
Page: 98 Status: 200
Page: 99 Status: 200
Page: 100 Status: 200
Page: 101 Status: 200
Page: 102 Status: 200
Page: 103 Status: 200
Page: 104 Status: 200
Page: 105 Status: 200
Page: 106 Status: 200
Page: 107 Status: 200
Page: 108 Status: 200
Page: 109 Status: 200
Page: 110 Status: 200
Page: 111 Status: 200
Page: 112 Status: 200
Page: 113 Status: 200
Page: 114 Status: 200
Page: 115 Status: 200
Page: 116 Status: 200
Page: 117 Status: 200
Page: 118 Status: 200
Page: 119 Status: 200
Page: 120 Status: 200
Page: 121 Status: 200
Page: 122 Status: 200
Page: 123 Status: 200
Page: 124 Status: 200
Page: 125 Status: 200
Page: 126 Status: 200
Page: 127 Status: 200
Page: 128 Status: 200
Page: 129 Status: 200
Page: 130 Status: 200
Page: 131 Status: 200
Page: 132 Status: 200
Page: 133 Status: 200
Page: 134 Status: 200
Page: 135 Status: 200
Page: 136 Status: 200
Page: 137 Status: 200
Page: 138 Status: 200
Page: 139 Status: 200
Page: 140 Status: 200
Page: 141 Status: 200
Page: 142 Status: 200
Page: 143 Status: 200
Page: 144 Status: 200
Page: 145 Status: 200
Page: 146 Status: 200
Page: 147 Status: 200
Page: 148 Status: 200
Page: 149 Status: 200
Page: 150 Status: 200
Page: 151 Status: 200
Page: 152 Status: 200
Page: 153 Status: 200
Page: 154 Status: 200
Page: 155 Status: 200
Page: 156 Status: 200
Page: 157 Status: 200
Page: 158 Status: 200
Page: 159 Status: 200
Page: 160 Status: 200
Page: 161 Status: 200
Page: 162 Status: 200
Page: 163 Status: 200
Page: 164 Status: 200
Page: 165 Status: 200
Page: 166 Status: 200
Page: 167 Status: 200
Page: 168 Status: 200
Page: 169 Status: 200
Page: 170 Status: 200
Page: 171 Status: 200
Page: 172 Status: 200
Page: 173 Status: 200
Page: 174 Status: 200
Page: 175 Status: 200
Page: 176 Status: 200
Page: 177 Status: 200
Page: 178 Status: 200
Page: 179 Status: 200
Page: 180 Status: 200
Page: 181 Status: 200
Page: 182 Status: 200
Page: 183 Status: 200
Page: 184 Status: 200
Page: 185 Status: 200
Page: 186 Status: 200
Page: 187 Status: 200
Page: 188 Status: 200
Page: 189 Status: 200
Page: 190 Status: 200
Page: 191 Status: 200
Page: 192 Status: 200
Page: 193 Status: 200
Page: 194 Status: 200
Page: 195 Status: 200
Page: 196 Status: 200
Page: 197 Status: 200
Page: 198 Status: 200
Page: 199 Status: 200
(3980, 6)

In [16]:
df.shape

(3980, 6)

In [17]:
df

,id,title,overview,popularity,vote_average,vote_count
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,1110.5450,7.884,2258
1,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",586.1293,7.987,3304
2,1288445,Mutiny,After witnessing his billionaire boss' murder ...,472.8163,6.349,225
3,1516698,The Last Sunrise,"Ry, a college student with a chronic illness, ...",308.5632,7.200,46
4,1621552,Facing El Chapo,Two Mexican officers must survive the final ho...,298.9748,8.730,315
...,...,...,...,...,...,...
3975,1052280,It's What's Inside,A pre-wedding reunion descends into a psycholo...,6.5307,6.474,854
3976,11001,Blue Streak,Miles Logan is a jewel thief who just hit the ...,7.3141,6.517,1687
3977,464889,Sniper: Ultimate Kill,"For the first time, Brandon Beckett, Richard M...",6.1744,6.434,385
3978,418680,Goodbye Christopher Robin,The behind the scenes story of the life of A.A...,6.4702,7.019,915
3979,10010,Brother Bear 2,Kenai finds his childhood human friend Nita an...,6.5062,6.658,1590

In [18]:
df.to_csv('movies.csv')